# Generated by Django 6.1.2 on 2026-10-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Security', 'Security'), ('Finance', 'Finance'), ('HR', 'HR'), ('Operations', 'Operations'), ('Legal', 'Legal'), ('Other', 'Other')], default='Other', max_length=50)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('chunks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Ready', 'Ready'), ('Failed', 'Failed')], default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
