# Generated by Django 6.1.2 on 2026-10-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('claimed_policy', models.CharField(blank=True, max_length=255)),
                ('claimed_page', models.CharField(blank=True, max_length=50)),
                ('evidence', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
