# Generated by Django 6.1.2 on 2026-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_policyevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_preview', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-compliant'), ('NEEDS_REVIEW', 'Needs review'), ('ERROR', 'Error')], default='NEEDS_REVIEW', max_length=20)),
                ('retrieval_ms', models.FloatField(default=0)),
                ('generation_ms', models.FloatField(default=0)),
                ('total_ms', models.FloatField(default=0)),
                ('retrieved_chunks', models.PositiveIntegerField(default=0)),
                ('search_mode', models.CharField(default='vector', max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
